<a href="https://colab.research.google.com/github/Iffraah96/ShopSense-AI/blob/main/notebook/01_Data_Loading_and_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛍️ ShopSense AI: AI-Powered Customer Review Intelligence System

## Notebook 1: Data Loading & Cleaning

### Project Overview

This notebook is the first step in building **ShopSense AI**, an AI-powered customer review intelligence system.

The goal of this notebook is to prepare the Women's E-Commerce Clothing Reviews dataset for analysis and machine learning.

---

## Objectives

In this notebook, we will:

- Import the required libraries
- Load the dataset
- Explore the dataset structure
- Check for missing values
- Check for duplicate records
- Clean column names
- Handle missing values
- Save the cleaned dataset

The cleaned dataset will be used in all future notebooks.

## Import Libraries

In [1]:
# General Libraries
import pandas as pd
import numpy as np
import os
import math

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Supperissing warnings
import warnings
warnings.filterwarnings('ignore')

## Load Dataset

In [2]:
df = pd.read_csv('/content/Womens Clothing E-Commerce Reviews.csv')
df.head()

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [3]:
df.shape

(23486, 11)

In [4]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [5]:
df.size

258346

In [6]:
df.dtypes

Unnamed: 0                  int64
Clothing ID                 int64
Age                         int64
Title                      object
Review Text                object
Rating                      int64
Recommended IND             int64
Positive Feedback Count     int64
Division Name              object
Department Name            object
Class Name                 object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               23486 non-null  int64
 1   Clothing ID              23486 non-null  int64
 2   Age                      23486 non-null  int64
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64
 6   Recommended IND          23486 non-null  int64
 7   Positive Feedback Count  23486 non-null  int64
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB

In [8]:
df.describe(include='all')

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
count,23486.000000,23486.000000,23486.000000,19676,22641,23486.000000,23486.000000,23486.000000,23472,23472,23472
unique,NaN,NaN,NaN,13993,22634,NaN,NaN,NaN,3,6,20
top,NaN,NaN,NaN,Love it!,Perfect fit and i've gotten so many compliment...,NaN,NaN,NaN,General,Tops,Dresses
freq,NaN,NaN,NaN,136,3,NaN,NaN,NaN,13850,10468,6319
mean,11742.500000,918.118709,43.198544,NaN,NaN,4.196032,0.822362,2.535936,NaN,NaN,NaN
std,6779.968547,203.298980,12.279544,NaN,NaN,1.110031,0.382216,5.702202,NaN,NaN,NaN
min,0.000000,0.000000,18.000000,NaN,NaN,1.000000,0.000000,0.000000,NaN,NaN,NaN
25%,5871.250000,861.000000,34.000000,NaN,NaN,4.000000,1.000000,0.000000,NaN,NaN,NaN
50%,11742.500000,936.000000,41.000000,NaN,NaN,5.000000,1.000000,1.000000,NaN,NaN,NaN
75%,17613.750000,1078.000000,52.000000,NaN,NaN,5.000000,1.000000,3.000000,NaN,NaN,NaN
max,23485.000000,1205.000000,99.000000,NaN,NaN,5.000000,1.000000,122.000000,NaN,NaN,NaN

In [10]:
#checking duplicate rows
df.duplicated().sum()

np.int64(0)

In [15]:
#Cleaning column names

# Removing extra spaces from column name
df.columns = df.columns.str.strip()

# Replacing space in columns name with underscore
df.columns = df.columns.str.replace(' ','_')

# Coverting column names into lower case
df.columns = df.columns.str.lower()

In [16]:
# Display cleaned column names
df.columns

Index(['unnamed:_0', 'clothing_id', 'age', 'title', 'review_text', 'rating',
       'recommended_ind', 'positive_feedback_count', 'division_name',
       'department_name', 'class_name'],
      dtype='object')

## Handling Missing Values

In [17]:
# Checking missing values
df.isnull().sum()/100

unnamed:_0                  0.00
clothing_id                 0.00
age                         0.00
title                      38.10
review_text                 8.45
rating                      0.00
recommended_ind             0.00
positive_feedback_count     0.00
division_name               0.14
department_name             0.14
class_name                  0.14
dtype: float64

In [18]:
# dropping column unnamed:_0
# This is an index column and does'nt contribute in the analysis

df.drop(columns=['unnamed:_0'], inplace=True)

In [19]:
df.head()

,clothing_id,age,title,review_text,rating,recommended_ind,positive_feedback_count,division_name,department_name,class_name
0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [20]:
#fill the null values in column 'title' with 'No title'
df["title"] = df["title"].fillna("No Title")

In [22]:
df.shape

(23486, 10)

In [23]:
# Remove Rows with Missing/null values in column 'Review Text'
df = df.dropna(subset=['review_text'])

# Check the new dataset shape
print("Updated Dataset Shape:", df.shape)

Updated Dataset Shape: (22641, 10)

In [25]:
# Replacing missing values in following columns with 'unknown'

df['division_name'] = df['division_name'].fillna('Unknown')
df['department_name'] = df['department_name'].fillna('Unknown')
df['class_name'] = df['class_name'].fillna('Unknown')

In [27]:
# Verify there are no missing values left
df.isnull().sum()

clothing_id                0
age                        0
title                      0
review_text                0
rating                     0
recommended_ind            0
positive_feedback_count    0
division_name              0
department_name            0
class_name                 0
dtype: int64

In [28]:
# Save the clean dataset

df.to_csv('clean_women_clothing_review_dataset.csv', index=False)

print('Cleaned dataset saved successfully..!')

Cleaned dataset saved successfully..!

## Summary

In this notebook, we successfully prepared the dataset for analysis.

### Tasks Completed

- Imported the required libraries
- Loaded the dataset
- Explored the dataset structure
- Identified missing values
- Removed the unnecessary index column
- Filled missing values in the Title column
- Removed rows with missing review text
- Filled missing values in categorical columns
- Saved the cleaned dataset

The cleaned dataset is now ready for **Exploratory Data Analysis (EDA)** in the next notebook.